import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {cycle} from '../../src/data/farm-play/cycle.mjs';
import {questions} from '../../src/data/farm-play/quiz.mjs';
const require=createRequire(import.meta.url);const {chromium}=require('playwright');
const base=process.env.FARM_PLAY_URL||'http://127.0.0.1:4331';
const screenshots=fileURLToPath(new URL('../../design-reference/screenshots/farm-play/',import.meta.url));await mkdir(screenshots,{recursive:true});
const browser=await chromium.launch({headless:true});const context=await browser.newContext();
// Observe actual Web Audio creation and oscillator lifetimes without replacing playback.
await context.addInitScript(()=>{window.__audio={created:0,started:0,stopped:0,suspended:0,closed:0,active:0};const Native=window.AudioContext;if(Native)window.AudioContext=class extends Native{constructor(...args){super(...args);window.__audio.created++;}createOscillator(){const o=super.createOscillator();const start=o.start.bind(o),stop=o.stop.bind(o);let active=false;o.start=(...args)=>{window.__audio.started++;window.__audio.active++;active=true;return start(...args);};o.stop=(...args)=>{window.__audio.stopped++;return stop(...args);};o.addEventListener('ended',()=>{if(active){active=false;window.__audio.active--;}});return o;}suspend(){window.__audio.suspended++;return super.suspend();}close(){window.__audio.closed++;try{sessionStorage.setItem('__farmPlayAudioClosed',String(window.__audio.closed));}catch{}return super.close();}};});
const page=await context.newPage();const errors=[],failed=[],externalFailures=[];let checks=0;
page.on('pageerror',error=>errors.push(error.message));page.on('console',msg=>{if(msg.type()==='error'){const url=msg.location().url;const host=(()=>{try{return new URL(url).hostname;}catch{return '';}})();if((host==='fonts.googleapis.com'||host==='fonts.gstatic.com')&&msg.text().includes('ERR_NETWORK_ACCESS_DENIED'))externalFailures.push({url,message:msg.text()});else errors.push(msg.text()+' '+url);}});page.on('response',r=>{if(r.url().startsWith(base)&&r.status()>=400)failed.push(r.url()+' '+r.status());});
const ok=(value,message)=>{assert.ok(value,message);checks++;};
const go=async slug=>{const response=await page.goto(base+'/choi-cung-nong-trai/'+slug,{waitUntil:'networkidle'});ok(response.status()===200,'Route '+slug);};
const shot=async name=>{await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.screenshot({path:screenshots+name+'.png',fullPage:true,animations:'disabled'});};
const farmProgress=()=>page.locator('[data-progress]').textContent();
const routes=['','mot-vong-nong-trai/','hom-nay-an-nam-gi/','ban-hieu-nam-toi-dau/'];
try {
 for(const width of [1440,1280,1024,768,390,375,320]){
  await page.setViewportSize({width,height:1000});for(const slug of routes){await go(slug);await page.evaluate(()=>document.fonts.ready);await shot((slug.split('/')[0]||'collection')+'-'+width);const geometry=await page.evaluate(()=>({page:document.documentElement.scrollWidth,viewport:innerWidth,tooWide:[...document.querySelectorAll('.farm-play *')].filter(el=>{const r=el.getBoundingClientRect();return r.width&& (r.left<-.5||r.right>innerWidth+.5);}).map(el=>el.className),broken:[...document.images].filter(i=>!i.complete||i.naturalWidth===0).map(i=>i.src)}));ok(geometry.page<=geometry.viewport,'Page overflow '+slug+' '+width);ok(!geometry.tooWide.length,'Section overflow '+slug+' '+width+' '+geometry.tooWide);ok(!geometry.broken.length,'Images loaded '+slug);}
 }
 await page.setViewportSize({width:1440,height:1000});
 await go('');const links=await page.locator('.play-activity .play-link').evaluateAll(a=>a.map(a=>a.getAttribute('href')));ok(new Set(links).size===3,'Collection links to all activities');
 await go('mot-vong-nong-trai/');ok(await page.evaluate(()=>window.__audio.created)===0,'Default silence, no AudioContext');
 await page.locator('[data-destination="byproducts"]').click();ok((await farmProgress()).startsWith('0'),'No unselected placement');
 await page.locator('[data-piece="mushrooms"]').click();await page.locator('[data-destination="byproducts"]').click();ok((await farmProgress()).startsWith('0'),'Wrong drop preserves progress');ok(await page.locator('[data-piece="mushrooms"]').getAttribute('aria-pressed')==='true','Wrong drop preserves selected piece');await shot('farm-incorrect-1440');
 await page.locator('[data-hint]').click();ok(await page.locator('[data-destination="mushrooms"]').getAttribute('data-hint')==='true','Hint targets selected piece');ok((await farmProgress()).startsWith('0'),'Hint does not complete step');
 await page.locator('.farm-pieces').evaluate(el=>el.scrollIntoView({block:'end',behavior:'instant'}));await page.locator('[data-piece="mushrooms"]').dragTo(page.locator('[data-destination="mushrooms"]'));ok((await farmProgress()).startsWith('1'),'Desktop drag places piece');await shot('farm-in-progress-1440');
 await page.locator('[data-destination="mushrooms"]').evaluate(el=>el.click());ok((await farmProgress()).startsWith('1'),'Duplicate destination cannot increment');
 for(const step of cycle.filter(s=>s.id!=='mushrooms')){await page.locator('[data-piece="'+step.id+'"]').focus();await page.keyboard.press('Space');await page.locator('[data-destination="'+step.id+'"]').focus();await page.keyboard.press('Enter');}
 ok((await farmProgress()).startsWith('5'),'Keyboard completes all steps');ok(await page.locator('[data-complete]').isVisible(),'Farm completion revealed');ok(await page.locator('[data-complete] h2').evaluate(el=>el===document.activeElement),'Farm completion focus');await shot('farm-complete-1440');
 await page.locator('[data-reset]').click();ok((await farmProgress()).startsWith('0'),'Farm replay resets');ok(await page.locator('[data-piece]:disabled').count()===0,'Farm replay restores pieces');
 // Mobile tap-only placement and replay.
 const touch=await browser.newContext({viewport:{width:375,height:850},isMobile:true,hasTouch:true});const mobile=await touch.newPage();await mobile.goto(base+'/choi-cung-nong-trai/mot-vong-nong-trai/',{waitUntil:'networkidle'});for(const step of cycle){await mobile.locator('[data-piece="'+step.id+'"]').tap();await mobile.locator('[data-destination="'+step.id+'"]').tap();}ok((await mobile.locator('[data-progress]').textContent()).startsWith('5'),'Mobile tap completion');await mobile.screenshot({path:screenshots+'farm-complete-375.png',fullPage:true});await mobile.locator('[data-reset]').tap();ok((await mobile.locator('[data-progress]').textContent()).startsWith('0'),'Mobile replay');await touch.close();
 // Explicit audio activation and remembered preferences without autoplay.
 await page.locator('[data-sound-toggle]').click();ok(await page.locator('[data-sound-toggle]').getAttribute('aria-pressed')==='true','Sound toggle enables');await page.waitForTimeout(250);const starts=await page.evaluate(()=>window.__audio.started);await page.locator('[data-piece="byproducts"]').evaluate(el=>{for(let i=0;i<10;i++)el.click();});ok(await page.evaluate(()=>window.__audio.started)===starts+1,'Rapid clicks produce one effect');
 await page.locator('[data-music-toggle]').click();ok(await page.locator('[data-music-toggle]').getAttribute('aria-pressed')==='true','Music toggle enables');ok(await page.evaluate(()=>window.__audio.started)>starts+1,'Music creates original notes');
 // Synthetic visibility events exercise the same handler used for actual tab hiding.
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});await page.waitForTimeout(100);ok(await page.evaluate(()=>window.__audio.suspended)===1,'Hidden tab suspends audio');
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>false});document.dispatchEvent(new Event('visibilitychange'));});await page.waitForFunction(expected=>window.__audio.started>expected,starts+4);ok(await page.evaluate(()=>window.__audio.started)>starts+4,'Visible tab resumes activated music');
 await page.locator('[data-music-toggle]').click();ok(await page.locator('[data-music-toggle]').getAttribute('aria-pressed')==='false','Music off');await page.locator('[data-sound-toggle]').click();ok(await page.locator('[data-sound-toggle]').getAttribute('aria-pressed')==='false','Sound off');
 await page.locator('[data-sound-toggle]').click();await page.locator('[data-music-toggle]').click();await page.locator('.play-related a[href="/choi-cung-nong-trai/hom-nay-an-nam-gi/"]').click();await page.waitForLoadState('networkidle');ok(await page.evaluate(()=>window.__audio.created)===0,'Remembered preferences never autoplay');ok(await page.evaluate(()=>sessionStorage.getItem('__farmPlayAudioClosed'))==='1','Leaving activity closes its audio context');ok(await page.locator('[data-sound-toggle]').getAttribute('aria-pressed')==='true','Sound preference remembered');ok(await page.locator('[data-music-toggle]').getAttribute('aria-pressed')==='true','Music preference remembered');
 await page.locator('[data-sound-toggle]').click();await page.locator('[data-music-toggle]').click();await page.locator('[data-music-toggle]').click();
 // Kitchen: each flavor/time combination, shopping list, alternatives and details.
 for(const flavor of ['light','rich','crisp'])for(const time of ['15','30','leisure']){await page.locator('input[name="flavor"][value="'+flavor+'"]').check();await page.locator('input[name="time"][value="'+time+'"]').check();await page.locator('.meal-submit').click();if(flavor==='crisp'&&time!=='leisure'){ok(await page.locator('[data-no-match]').isVisible(),'Honest no-match '+time);}else{ok(await page.locator('[data-result]').isVisible(),'Recipe for '+flavor+' '+time);const text=await page.locator('[data-recipe-meta]').textContent();if(time!=='leisure')ok(Number(text.match(/(\d+) phút/)[1])<=Number(time),'Time budget enforced');}}
 await page.locator('input[value="crisp"]').check();await page.locator('input[value="15"]').check();await page.locator('.meal-submit').click();await shot('meal-no-match-1440');await page.locator('[data-relax]').click();ok(await page.locator('input[value="leisure"]').isChecked(),'No-match action makes specific adjustment');ok(await page.locator('[data-result]').isVisible(),'Adjustment finds recipe');
 await page.locator('input[value="rich"]').check();for(const key of ['rice','egg','greens'])await page.locator('input[value="'+key+'"]').check();await page.locator('input[value="tofu"]').check();await page.locator('input[value="tofu"]').uncheck();await page.locator('.meal-submit').click();ok(await page.locator('[data-recipe-title]').textContent()==='Cơm nấm áp chảo','Pantry ranking');ok((await page.locator('[data-missing]').textContent()).includes('nấm bào ngư'),'Missing mushrooms listed');ok(!(await page.locator('[data-missing]').textContent()).includes('cơm chín'),'Selected pantry excluded from shopping');await shot('meal-result-1440');
 await page.locator('[data-details-toggle]').click();ok(await page.locator('#recipe-details').isVisible(),'Full recipe revealed');ok(await page.locator('[data-details-heading]').evaluate(el=>el===document.activeElement),'Recipe focus moves to heading');ok(await page.locator('[data-steps] li').count()>=3,'Numbered instructions');await shot('meal-details-1440');await page.locator('[data-close-details]').click();ok(await page.locator('[data-details-toggle]').evaluate(el=>el===document.activeElement),'Collapse returns focus');
 const first=await page.locator('[data-recipe-title]').textContent();await page.waitForTimeout(200);const revealStart=await page.evaluate(()=>window.__audio.started);await page.locator('[data-alternative]').click();ok(await page.evaluate(()=>window.__audio.started)>revealStart,'Meal alternative plays opted-in reveal cue');ok(await page.locator('[data-recipe-title]').textContent()!==first,'Alternative changes meal');ok(!(await page.locator('#recipe-details').isVisible()),'Alternative closes stale details');
 await page.locator('input[value="light"]').check();await page.locator('input[value="15"]').check();await page.locator('.meal-submit').click();ok(await page.locator('[data-alternative]').isDisabled(),'Single match alternative handled');await page.locator('[data-product]').click();await page.waitForLoadState('networkidle');ok(await page.locator('#nam-bao-ngu').count()===1,'Product link points to real anchor');await page.goBack({waitUntil:'networkidle'});await page.locator('input[value="rich"]').check();await page.locator('input[value="15"]').check();await page.locator('.meal-submit').click();ok(await page.locator('[data-recipe-title]').textContent()==='Trứng xào nấm bào ngư','Navigation back stays functional');
 // Quiz: controlled mixed score, distinct IDs, double activation and replay.
 await go('ban-hieu-nam-toi-dau/');ok(await page.evaluate(()=>window.__audio.created)===0,'Quiz remembered preference stays silent');await page.locator('[data-sound-toggle]').click();await page.waitForTimeout(200);const quizAudioStart=await page.evaluate(()=>window.__audio.started);const seen=[];for(let i=0;i<5;i++){const id=await page.locator('[data-question]').getAttribute('data-question-id');seen.push(id);const q=questions.find(q=>q.id===id);const answer=i<3?q.correct:q.choices.find(c=>c.id!==q.correct).id;await page.locator('[data-answer="'+answer+'"]').evaluate(el=>{el.click();el.click();});ok(await page.locator('[data-answer]:disabled').count()===4,'Answer submission locks all choices');ok(await page.locator('[data-quiz-feedback]').textContent()===(i<3?'Đúng rồi! ':'Chưa đúng, mình cùng xem nhé. ')+q.explanation,'Verified answer explanation');if(i===0){ok(await page.evaluate(()=>window.__audio.started)>quizAudioStart,'Quiz correct answer plays an opted-in cue');await shot('quiz-correct-1440');}if(i===3)await shot('quiz-incorrect-1440');await page.locator('[data-next]').evaluate(el=>{el.click();el.click();});if(i<4)ok(await page.locator('[data-next]').isDisabled(),'Double next cannot skip question');}
 ok(new Set(seen).size===5,'Five distinct questions');ok(await page.locator('[data-score]').textContent()==='3 / 5 câu đúng','Accurate score despite repeated clicks');await shot('quiz-complete-1440');await page.locator('[data-replay]').click();ok(await page.locator('[data-quiz-progress]').textContent()==='Câu 1 / 5','Quiz replay progress');ok(await page.locator('[data-answer]:disabled').count()===0,'Replay unlocks answers');ok(await page.locator('[data-quiz-feedback]').textContent()==='','Replay clears feedback');
 await page.locator('.play-related a[href="/choi-cung-nong-trai/"]').click();await page.waitForLoadState('networkidle');await page.goBack({waitUntil:'networkidle'});const id=await page.locator('[data-question]').getAttribute('data-question-id');await page.locator('[data-answer="'+questions.find(q=>q.id===id).correct+'"]').click();ok(await page.locator('[data-next]').isEnabled(),'Quiz back navigation has single working listener');
 // Reduced motion disables every local animated state while interactions remain usable.
 await page.emulateMedia({reducedMotion:'reduce'});await go('mot-vong-nong-trai/');await page.locator('[data-piece="byproducts"]').click();await page.locator('[data-destination="byproducts"]').click();const motion=await page.locator('[data-destination="byproducts"] .destination-number').evaluate(el=>getComputedStyle(el).animationName);ok(motion==='none','Reduced motion prevents placement animation');ok((await farmProgress()).startsWith('1'),'Reduced motion preserves functionality');await shot('farm-reduced-motion-1440');await page.locator('[data-piece="substrate"]').focus();ok(await page.locator('[data-piece="substrate"]').evaluate(el=>getComputedStyle(el).outlineWidth==='3px'),'Visible keyboard focus');
 // Graceful local-storage denial and blocked playback, each in a fresh context.
 const denied=await browser.newContext();await denied.addInitScript(()=>{Storage.prototype.getItem=()=>{throw new Error('denied')};Storage.prototype.setItem=()=>{throw new Error('denied')};});const deniedPage=await denied.newPage();await deniedPage.goto(base+'/choi-cung-nong-trai/ban-hieu-nam-toi-dau/',{waitUntil:'networkidle'});await deniedPage.locator('[data-sound-toggle]').click();ok(await deniedPage.locator('[data-sound-toggle]').getAttribute('aria-pressed')==='true','Storage denial is nonblocking');await denied.close();
 const blocked=await browser.newContext();await blocked.addInitScript(()=>{window.AudioContext=class {state='suspended';resume(){return Promise.reject(new Error('blocked'));}close(){return Promise.resolve();}};});const blockedPage=await blocked.newPage();await blockedPage.goto(base+'/choi-cung-nong-trai/mot-vong-nong-trai/',{waitUntil:'networkidle'});await blockedPage.locator('[data-music-toggle]').click();ok((await blockedPage.locator('[data-audio-status]').textContent()).includes('chưa cho phép'),'Blocked audio explains retry');await blockedPage.locator('[data-piece="byproducts"]').click();await blockedPage.locator('[data-destination="byproducts"]').click();ok((await blockedPage.locator('[data-progress]').textContent()).startsWith('1'),'Blocked audio never blocks game');await blocked.close();
 ok(errors.length===0,'Console/page errors: '+errors.join('; '));ok(failed.length===0,'Failed local assets/routes: '+failed.join('; '));console.log(JSON.stringify({checks,viewports:[1440,1280,1024,768,390,375,320],routes:4,consoleErrors:errors,failedLocalRequests:failed,externalFontLimitations:[...new Set(externalFailures.map(e=>e.url))],screenshots},null,2));
} finally {await browser.close();}
